name: Development CI

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    environment:
      DB_URI: value
      PORT: 1
      HOST: value
      ACCESS_SECRET: value
      REFRESH_SECRET: value
      ACCESS_EXPIRE_TIME: 1
      REFRESH_EXPIRE_TIME: 1
      REDIS_HOST: value
      REDIS_PORT: 1

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - name: Run integration tests
        run: npm run test:e2e
